/* 사용자관리 */
CREATE TABLE `USERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(40) NOT NULL COMMENT '사용자ID',
  `NAME` VARCHAR(40) NOT NULL COMMENT '성명',
  `PASSWORD` VARCHAR(100) NOT NULL COMMENT '비밀번호',
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 개인별연차관리 */
CREATE TABLE `USER_ANNUAL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` bigint(20) NOT NULL COMMENT 'USER_ID',
  `YEAR` CHAR(4) NOT NULL COMMENT '년도',
  `DAYS` DECIMAL(5,1) NOT NULL COMMENT '연차일수',
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`ID`),
  CONSTRAINT `USER_ANNUAL_USER_ID_FK` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 휴가관리 */
CREATE TABLE `VACATION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_ANNUAL_ID` bigint(20) NOT NULL COMMENT 'USER_ANNUAL_ID',
  `VACATION_GB` CHAR(2) NOT NULL COMMENT '휴가구분(01:연차, 02:반차, 03:반반차)',
  `START_DT` CHAR(8) NOT NULL COMMENT '시작일자',
  `END_DT` CHAR(8) NOT NULL COMMENT '종료일자',
  `USE_DAYS` DECIMAL(5,1) NOT NULL COMMENT '사용일수',
  `COMMENT` VARCHAR(1000) COMMENT '코멘트',
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  PRIMARY KEY (`ID`),
  CONSTRAINT `VACATION_USER_ANNUAL_ID_FK` FOREIGN KEY (`USER_ANNUAL_ID`) REFERENCES `USER_ANNUAL` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;